pos_tag_En_to_Ja = {
"ADJ": "形容詞",
"ADP": "前置詞",
"ADV": "副詞",
"AUX": "助動詞",
"CONJ": "接続詞",
"CCONJ": "等位接続詞",
"DET": "限定詞",
"INTJ": "感動詞",
"NOUN": "名詞",
"NUM": "数字",
"PART": "接尾辞・小詞",
"PRON": "代名詞",
"PROPN": "固有名詞",
"PUNCT": "記号",
"SCONJ": "従属接続詞",
"SYM": "記号",
"VERB": "動詞",
"SPACE": "スペース"
}